### ISSUE TITLE
[BUGS] Under the single instance condition, AutoRefresh will not perform the refresh operation for the second time.

### ISSUE THREAD

**Issue by x1nchen** [mgtv-tech/jetcache-go#36]
RT， minimum reproducible code as below

lib version

- github.com/mgtv-tech/jetcache-go v1.1.8
- github.com/redis/go-redis/v9 v9.6.1

```golang
package main

import (
	"context"
	"fmt"
	"math/rand"
	"time"

	cache "github.com/mgtv-tech/jetcache-go"
	"github.com/mgtv-tech/jetcache-go/remote"
	"github.com/redis/go-redis/v9"
)

func main() {
	client := redis.NewClient(&redis.Options{
		Addr: "127.0.0.1:6379",
	})

	jetcache := cache.New(
		cache.WithName("test"),
		cache.WithRemote(remote.NewGoRedisV9Adapter(client)),
		cache.WithRefreshDuration(20*time.Second),
		cache.WithStopRefreshAfterLastAccess(24*time.Hour),
	)
	var value string
	err := jetcache.Once(context.Background(), "test",
		cache.TTL(time.Minute),
		cache.Refresh(true),
		cache.Value(&value),
		cache.Do(func(ctx context.Context) (any, error) {
			var s = "AAA"
			if rand.Int31()%2 == 0 {
				s = "BBB"
			}
			fmt.Println("query value", s)
			return s, nil
		}),
	)
	if err != nil {
		panic(err)
	}

	time.Sleep(5 * time.Minute)
}
```

The code execution results are as follows: 

![image](https://github.com/user-attachments/assets/cff190ab-c873-460b-bc02-c8404913dcd4)

Possible reasons：

When the refresh was performed for the second time, the lockkey ttl had not yet expired, causing this refresh to not occur.

**Comment by daoshenzzg** [comment]
Thank you for reporting this bug. After analysis, we've reached the following conclusions:

1. The bug exists: The refresh task executes correctly at the 20-second mark on the first attempt, but subsequent executions often take approximately 40 seconds. This is because the lock key's TTL in the remote.SetNX operation is 20 seconds (equal to refreshDuration). The network I/O time required for the Redis command creates a timing discrepancy, causing the bug.
2. Because remote.SetNX employs a non-strict lock, this bug is unavoidable.
3. As more cache instances utilize the AutoRefresh feature, the refresh execution frequency approaches 20 seconds.

Therefore, we've implemented a simple fix:
```go
lockTimeout := c.refreshDuration - 10 * time.Millisecond
ok, err := c.remote.SetNX(ctx, lockKey, strconv.FormatInt(now.Unix(), 10), lockTimeout)
```

Regarding the AutoRefresh feature's usage scenario ("Suitable for scenarios with few keys, low real-time requirements, and very high loading overhead"), "few keys" requires clarification.

To determine an appropriate number of keys, you can create a model. For example, with `refreshConcurrency=10`, 5 application servers, an average loading time of 2 seconds per key, and refreshDuration=30s, the theoretical maximum number of refreshable keys is 30 / 2 * 10 * 5 = 750.
